import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Insets;
import javafx.geometry.Orientation;
import javafx.scene.Scene;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;

public class CheckBoxDemo2 extends Application {
	
	CheckBox keyboardCheckBox;
	CheckBox mouseCheckBox;
	CheckBox touchScreenCheckBox;
	
	Label responseLabel;
	Label selectedLabel;
	Label headingLabel;
	
	String inputDeviceString = "";

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		launch(args);

	}

	@Override
	public void start(Stage primaryStage) throws Exception {
		// TODO Auto-generated method stub
		primaryStage.setTitle("Demonstrate Check Boxes");
		
		FlowPane pane = new FlowPane(Orientation.VERTICAL, 0, 10);
		
		Insets insets = new Insets(0, 0, 0, 10);
		
		pane.setPadding(insets);
		
		Scene scene = new Scene(pane, 300, 180);
		
		primaryStage.setScene(scene);
		
		headingLabel = new Label("Select input devices ");
		
		// Create a label that will report the state of the selected check box.
		responseLabel = new Label("Supported devices: <none>");
		
		// Create check boxes
		keyboardCheckBox = new CheckBox("Keyboard");
		mouseCheckBox = new CheckBox("Mouse");
		touchScreenCheckBox = new CheckBox("TouchScreen");
		
		// To specify a handler for an event generated by the source, i.e. a check box in this case.
		keyboardCheckBox.setOnAction(new EventHandler<ActionEvent>() {
			
			@Override
			public void handle(ActionEvent arg0) {  // arg0 is the event that was generated. 
				// TODO Auto-generated method stub
				
				if (keyboardCheckBox.isSelected()) {
					responseLabel.setText("Keyboard selected.");
				} else {
					responseLabel.setText("Keyboard cleared.");
				}
				
			}
		});
		
		mouseCheckBox.setOnAction(new EventHandler<ActionEvent>() {

			@Override
			public void handle(ActionEvent arg0) {
				// Obtain the state of a check box by calling isSelected().
				if (mouseCheckBox.isSelected()) {
					responseLabel.setText("Mouse selected.");
				} else {
					responseLabel.setText("Mouse cleared.");
				}
			}
		});
		
		// To specify the handler in charge of the event generated by the control, i.e. check box in this case.
		touchScreenCheckBox.setOnAction(new EventHandler<ActionEvent>() {

			@Override
			public void handle(ActionEvent arg0) {
				// Obtain the state of a check box by calling isSelected().
				if (touchScreenCheckBox.isSelected()) {
					responseLabel.setText("Touch Screen selected.");
				} else {
					responseLabel.setText("Touch Screen cleared.");
				}
			}
		});
		
		// Add controls to the scene graph.
		pane.getChildren().addAll(headingLabel, keyboardCheckBox, mouseCheckBox, touchScreenCheckBox, responseLabel, selectedLabel);
		
		primaryStage.show();
	}

}
